### PR TITLE
Create deploy-to-edgio.md

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by ayrton** [comment]
For larger pull requests, such as language/framework quickstarts, we kindly ask that you [open an issue](https://github.com/planetscale/docs/issues) to request the new content. Thank you

**Comment by rishi-raj-jain** [comment]
@ayrton 

Umm, that PR explains how to deploy to [Edgio](https://edg.io) (which is not a framework/language). Does that clarify?

**Comment by hollylawly** [comment]
> @ayrton
> 
> Umm, that PR explains how to deploy to [Edgio](https://edg.io) (which is not a framework/language). Does that clarify?

Hey Rishi! This is the full text from our readme:

>If you have a fix for an existing issue or you found a typo/bug, you can [open a new PR](https://github.com/planetscale/docs/pulls) in this repo.
>
>For larger pull requests, such as language/framework quickstarts, we ask that you [open an issue](https://github.com/planetscale/docs/issues) to request the new content instead of creating it yourself.

We only accept PRs that are updates to _existing_ docs. If you are proposing a large PR that introduces a brand new doc, we ask you create an issue first.

**Comment by rishi-raj-jain** [comment]
@hollylawly Thank you so much for being open and explaining, I'm following it now. Pardon the incoveniences.

**Pull request closed without merging**
